// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileformat.proto

package net.morbz.osmonaut.binary.pbf.proto;

public final class Fileformat {
  private Fileformat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Blob)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>optional bytes raw = 1;</code>
     */
    boolean hasRaw();
    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>optional bytes raw = 1;</code>
     */
    com.google.protobuf.ByteString getRaw();

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     */
    boolean hasRawSize();
    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     */
    int getRawSize();

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>optional bytes zlib_data = 3;</code>
     */
    boolean hasZlibData();
    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>optional bytes zlib_data = 3;</code>
     */
    com.google.protobuf.ByteString getZlibData();

    /**
     * <pre>
     * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
     * </pre>
     *
     * <code>optional bytes lzma_data = 4;</code>
     */
    boolean hasLzmaData();
    /**
     * <pre>
     * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
     * </pre>
     *
     * <code>optional bytes lzma_data = 4;</code>
     */
    com.google.protobuf.ByteString getLzmaData();

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Depreciated in 2010.
     * </pre>
     *
     * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated boolean hasOBSOLETEBzip2Data();
    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Depreciated in 2010.
     * </pre>
     *
     * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated com.google.protobuf.ByteString getOBSOLETEBzip2Data();
  }
  /**
   * Protobuf type {@code Blob}
   */
  public  static final class Blob extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Blob)
      BlobOrBuilder {
    // Use Blob.newBuilder() to construct.
    private Blob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Blob() {
      raw_ = com.google.protobuf.ByteString.EMPTY;
      rawSize_ = 0;
      zlibData_ = com.google.protobuf.ByteString.EMPTY;
      lzmaData_ = com.google.protobuf.ByteString.EMPTY;
      oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Blob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              raw_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rawSize_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              zlibData_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              lzmaData_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              oBSOLETEBzip2Data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_Blob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_Blob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.class, net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.Builder.class);
    }

    private int bitField0_;
    public static final int RAW_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString raw_;
    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>optional bytes raw = 1;</code>
     */
    public boolean hasRaw() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>optional bytes raw = 1;</code>
     */
    public com.google.protobuf.ByteString getRaw() {
      return raw_;
    }

    public static final int RAW_SIZE_FIELD_NUMBER = 2;
    private int rawSize_;
    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     */
    public boolean hasRawSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     */
    public int getRawSize() {
      return rawSize_;
    }

    public static final int ZLIB_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString zlibData_;
    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>optional bytes zlib_data = 3;</code>
     */
    public boolean hasZlibData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>optional bytes zlib_data = 3;</code>
     */
    public com.google.protobuf.ByteString getZlibData() {
      return zlibData_;
    }

    public static final int LZMA_DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString lzmaData_;
    /**
     * <pre>
     * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
     * </pre>
     *
     * <code>optional bytes lzma_data = 4;</code>
     */
    public boolean hasLzmaData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
     * </pre>
     *
     * <code>optional bytes lzma_data = 4;</code>
     */
    public com.google.protobuf.ByteString getLzmaData() {
      return lzmaData_;
    }

    public static final int OBSOLETE_BZIP2_DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString oBSOLETEBzip2Data_;
    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Depreciated in 2010.
     * </pre>
     *
     * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasOBSOLETEBzip2Data() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Depreciated in 2010.
     * </pre>
     *
     * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
      return oBSOLETEBzip2Data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, raw_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rawSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, zlibData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, lzmaData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, oBSOLETEBzip2Data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, raw_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rawSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, zlibData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, lzmaData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, oBSOLETEBzip2Data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob)) {
        return super.equals(obj);
      }
      net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob other = (net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob) obj;

      boolean result = true;
      result = result && (hasRaw() == other.hasRaw());
      if (hasRaw()) {
        result = result && getRaw()
            .equals(other.getRaw());
      }
      result = result && (hasRawSize() == other.hasRawSize());
      if (hasRawSize()) {
        result = result && (getRawSize()
            == other.getRawSize());
      }
      result = result && (hasZlibData() == other.hasZlibData());
      if (hasZlibData()) {
        result = result && getZlibData()
            .equals(other.getZlibData());
      }
      result = result && (hasLzmaData() == other.hasLzmaData());
      if (hasLzmaData()) {
        result = result && getLzmaData()
            .equals(other.getLzmaData());
      }
      result = result && (hasOBSOLETEBzip2Data() == other.hasOBSOLETEBzip2Data());
      if (hasOBSOLETEBzip2Data()) {
        result = result && getOBSOLETEBzip2Data()
            .equals(other.getOBSOLETEBzip2Data());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRaw()) {
        hash = (37 * hash) + RAW_FIELD_NUMBER;
        hash = (53 * hash) + getRaw().hashCode();
      }
      if (hasRawSize()) {
        hash = (37 * hash) + RAW_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getRawSize();
      }
      if (hasZlibData()) {
        hash = (37 * hash) + ZLIB_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getZlibData().hashCode();
      }
      if (hasLzmaData()) {
        hash = (37 * hash) + LZMA_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getLzmaData().hashCode();
      }
      if (hasOBSOLETEBzip2Data()) {
        hash = (37 * hash) + OBSOLETE_BZIP2_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getOBSOLETEBzip2Data().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Blob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Blob)
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_Blob_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_Blob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.class, net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.Builder.class);
      }

      // Construct using net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        raw_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        rawSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        zlibData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        lzmaData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_Blob_descriptor;
      }

      public net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob getDefaultInstanceForType() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.getDefaultInstance();
      }

      public net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob build() {
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob buildPartial() {
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob result = new net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.raw_ = raw_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rawSize_ = rawSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.zlibData_ = zlibData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lzmaData_ = lzmaData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.oBSOLETEBzip2Data_ = oBSOLETEBzip2Data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob) {
          return mergeFrom((net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob other) {
        if (other == net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob.getDefaultInstance()) return this;
        if (other.hasRaw()) {
          setRaw(other.getRaw());
        }
        if (other.hasRawSize()) {
          setRawSize(other.getRawSize());
        }
        if (other.hasZlibData()) {
          setZlibData(other.getZlibData());
        }
        if (other.hasLzmaData()) {
          setLzmaData(other.getLzmaData());
        }
        if (other.hasOBSOLETEBzip2Data()) {
          setOBSOLETEBzip2Data(other.getOBSOLETEBzip2Data());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString raw_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>optional bytes raw = 1;</code>
       */
      public boolean hasRaw() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>optional bytes raw = 1;</code>
       */
      public com.google.protobuf.ByteString getRaw() {
        return raw_;
      }
      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>optional bytes raw = 1;</code>
       */
      public Builder setRaw(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        raw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>optional bytes raw = 1;</code>
       */
      public Builder clearRaw() {
        bitField0_ = (bitField0_ & ~0x00000001);
        raw_ = getDefaultInstance().getRaw();
        onChanged();
        return this;
      }

      private int rawSize_ ;
      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       */
      public boolean hasRawSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       */
      public int getRawSize() {
        return rawSize_;
      }
      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       */
      public Builder setRawSize(int value) {
        bitField0_ |= 0x00000002;
        rawSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       */
      public Builder clearRawSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rawSize_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString zlibData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>optional bytes zlib_data = 3;</code>
       */
      public boolean hasZlibData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>optional bytes zlib_data = 3;</code>
       */
      public com.google.protobuf.ByteString getZlibData() {
        return zlibData_;
      }
      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>optional bytes zlib_data = 3;</code>
       */
      public Builder setZlibData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        zlibData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>optional bytes zlib_data = 3;</code>
       */
      public Builder clearZlibData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        zlibData_ = getDefaultInstance().getZlibData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString lzmaData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
       * </pre>
       *
       * <code>optional bytes lzma_data = 4;</code>
       */
      public boolean hasLzmaData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
       * </pre>
       *
       * <code>optional bytes lzma_data = 4;</code>
       */
      public com.google.protobuf.ByteString getLzmaData() {
        return lzmaData_;
      }
      /**
       * <pre>
       * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
       * </pre>
       *
       * <code>optional bytes lzma_data = 4;</code>
       */
      public Builder setLzmaData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        lzmaData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
       * </pre>
       *
       * <code>optional bytes lzma_data = 4;</code>
       */
      public Builder clearLzmaData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lzmaData_ = getDefaultInstance().getLzmaData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Depreciated in 2010.
       * </pre>
       *
       * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       */
      @java.lang.Deprecated public boolean hasOBSOLETEBzip2Data() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Depreciated in 2010.
       * </pre>
       *
       * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       */
      @java.lang.Deprecated public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
        return oBSOLETEBzip2Data_;
      }
      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Depreciated in 2010.
       * </pre>
       *
       * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setOBSOLETEBzip2Data(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        oBSOLETEBzip2Data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Depreciated in 2010.
       * </pre>
       *
       * <code>optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearOBSOLETEBzip2Data() {
        bitField0_ = (bitField0_ & ~0x00000010);
        oBSOLETEBzip2Data_ = getDefaultInstance().getOBSOLETEBzip2Data();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Blob)
    }

    // @@protoc_insertion_point(class_scope:Blob)
    private static final net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob();
    }

    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Blob>
        PARSER = new com.google.protobuf.AbstractParser<Blob>() {
      public Blob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Blob(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Blob> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Blob> getParserForType() {
      return PARSER;
    }

    public net.morbz.osmonaut.binary.pbf.proto.Fileformat.Blob getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlobHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BlobHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional bytes indexdata = 2;</code>
     */
    boolean hasIndexdata();
    /**
     * <code>optional bytes indexdata = 2;</code>
     */
    com.google.protobuf.ByteString getIndexdata();

    /**
     * <code>required int32 datasize = 3;</code>
     */
    boolean hasDatasize();
    /**
     * <code>required int32 datasize = 3;</code>
     */
    int getDatasize();
  }
  /**
   * Protobuf type {@code BlobHeader}
   */
  public  static final class BlobHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BlobHeader)
      BlobHeaderOrBuilder {
    // Use BlobHeader.newBuilder() to construct.
    private BlobHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlobHeader() {
      type_ = "";
      indexdata_ = com.google.protobuf.ByteString.EMPTY;
      datasize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlobHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              indexdata_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              datasize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_BlobHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_BlobHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.class, net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString indexdata_;
    /**
     * <code>optional bytes indexdata = 2;</code>
     */
    public boolean hasIndexdata() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes indexdata = 2;</code>
     */
    public com.google.protobuf.ByteString getIndexdata() {
      return indexdata_;
    }

    public static final int DATASIZE_FIELD_NUMBER = 3;
    private int datasize_;
    /**
     * <code>required int32 datasize = 3;</code>
     */
    public boolean hasDatasize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 datasize = 3;</code>
     */
    public int getDatasize() {
      return datasize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatasize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, datasize_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, datasize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader)) {
        return super.equals(obj);
      }
      net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader other = (net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && (hasIndexdata() == other.hasIndexdata());
      if (hasIndexdata()) {
        result = result && getIndexdata()
            .equals(other.getIndexdata());
      }
      result = result && (hasDatasize() == other.hasDatasize());
      if (hasDatasize()) {
        result = result && (getDatasize()
            == other.getDatasize());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasIndexdata()) {
        hash = (37 * hash) + INDEXDATA_FIELD_NUMBER;
        hash = (53 * hash) + getIndexdata().hashCode();
      }
      if (hasDatasize()) {
        hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
        hash = (53 * hash) + getDatasize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlobHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BlobHeader)
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_BlobHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_BlobHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.class, net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.Builder.class);
      }

      // Construct using net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        indexdata_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        datasize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.internal_static_BlobHeader_descriptor;
      }

      public net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader getDefaultInstanceForType() {
        return net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.getDefaultInstance();
      }

      public net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader build() {
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader buildPartial() {
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader result = new net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.indexdata_ = indexdata_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.datasize_ = datasize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader) {
          return mergeFrom((net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader other) {
        if (other == net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasIndexdata()) {
          setIndexdata(other.getIndexdata());
        }
        if (other.hasDatasize()) {
          setDatasize(other.getDatasize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasDatasize()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString indexdata_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes indexdata = 2;</code>
       */
      public boolean hasIndexdata() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes indexdata = 2;</code>
       */
      public com.google.protobuf.ByteString getIndexdata() {
        return indexdata_;
      }
      /**
       * <code>optional bytes indexdata = 2;</code>
       */
      public Builder setIndexdata(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        indexdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes indexdata = 2;</code>
       */
      public Builder clearIndexdata() {
        bitField0_ = (bitField0_ & ~0x00000002);
        indexdata_ = getDefaultInstance().getIndexdata();
        onChanged();
        return this;
      }

      private int datasize_ ;
      /**
       * <code>required int32 datasize = 3;</code>
       */
      public boolean hasDatasize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 datasize = 3;</code>
       */
      public int getDatasize() {
        return datasize_;
      }
      /**
       * <code>required int32 datasize = 3;</code>
       */
      public Builder setDatasize(int value) {
        bitField0_ |= 0x00000004;
        datasize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 datasize = 3;</code>
       */
      public Builder clearDatasize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        datasize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BlobHeader)
    }

    // @@protoc_insertion_point(class_scope:BlobHeader)
    private static final net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader();
    }

    public static net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BlobHeader>
        PARSER = new com.google.protobuf.AbstractParser<BlobHeader>() {
      public BlobHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlobHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlobHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlobHeader> getParserForType() {
      return PARSER;
    }

    public net.morbz.osmonaut.binary.pbf.proto.Fileformat.BlobHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Blob_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Blob_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlobHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlobHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020fileformat.proto\"l\n\004Blob\022\013\n\003raw\030\001 \001(\014\022" +
      "\020\n\010raw_size\030\002 \001(\005\022\021\n\tzlib_data\030\003 \001(\014\022\021\n\t" +
      "lzma_data\030\004 \001(\014\022\037\n\023OBSOLETE_bzip2_data\030\005" +
      " \001(\014B\002\030\001\"?\n\nBlobHeader\022\014\n\004type\030\001 \002(\t\022\021\n\t" +
      "indexdata\030\002 \001(\014\022\020\n\010datasize\030\003 \002(\005B\'\n#net" +
      ".morbz.osmonaut.binary.pbf.protoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Blob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Blob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Blob_descriptor,
        new java.lang.String[] { "Raw", "RawSize", "ZlibData", "LzmaData", "OBSOLETEBzip2Data", });
    internal_static_BlobHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BlobHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlobHeader_descriptor,
        new java.lang.String[] { "Type", "Indexdata", "Datasize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
